version: '3.3'

services:
   django:
     container_name: web-backend
     build:
       context: ./api
     ports:
       - 8000:8000
   react:
     container_name: web-frontend
     build:
       context: ./frontend
     ports:
       - 3000:3000
